require "paq-nvim" {
  "savq/paq-nvim",
  "neovim/nvim-lsp",
  "neovim/nvim-lspconfig",
  "kabouzeid/nvim-lspinstall",
  "kdheepak/tabline.nvim",
  "hoob3rt/lualine.nvim",
  "kyazdani42/nvim-web-devicons",
  "yashguptaz/calvera-dark.nvim",
  "lewis6991/gitsigns.nvim",
  "Yggdroot/indentLine",
  {"nvim-treesitter/nvim-treesitter", run = ":TSUpdate"},
  "hrsh7th/nvim-compe",
  "rmagatti/auto-session",
  "rmagatti/session-lens",
  "crispgm/telescope-heading.nvim",
  "nvim-lua/popup.nvim",
  "nvim-lua/plenary.nvim",
  "nvim-telescope/telescope.nvim",
  "benmills/vimux",
  "janko-m/vim-test",
  "benmills/vimux",
  "b3nj5m1n/kommentary",
  "w0rp/ale",
  "mhartington/formatter.nvim",
  "mattn/emmet-vim",
  "AndrewRadev/tagalong.vim"
}
