vim.g.spaceline_colorscheme = 'space'
vim.g.spaceline_seperate_style = 'arrow'
vim.g.spaceline_diff_tool = 'git-gutter'
vim.g.spaceline_git_branch_icon = ''
vim.g.spaceline_diagnostic_tool= 'nvim_lsp'
