require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
-- require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
-- require("user.null-ls")
require("user.lualine")
require("user.toggleterm")
require("user.vim-test")
require("user.indentline")
require("user.autosession")
require("user.whichkey")
require("user.ale")

vim.lsp.set_log_level("debug")
