require('settings')
require('maps')
require('plugins')

require('plugins.telescope')
require('plugins.calvera')
require('plugins.lualine')
require('plugins.nvim-compe')
require('plugins.nvim-lspconfig')
require('plugins.nvim-treesitter')
require('plugins.vim-test')
require('plugins.ale')
require('plugins.gitsigns')
require('plugins.emmet')
require('plugins.tabline')
